# Generated by Django 5.2.4 on 2025-11-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPortfolioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.portfolio')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
